apiVersion: v1
entries:
  cert-manager-certs:
  - apiVersion: v1
    appVersion: v1.0.3
    created: "2020-10-28T12:50:50.628979581-06:00"
    description: A Helm chart for cert-manager and certs
    digest: 013f1f52d0debc9e1a84280d6d7100766a1c0473f802e53cc54c0b1d26d43f97
    name: cert-manager-certs
    type: application
    urls:
    - cert-manager-certs/cert-manager-certs-v1.0.3.tgz
    version: v1.0.3
  cloud-credentials:
  - apiVersion: v1
    created: "2020-10-28T12:50:50.629110339-06:00"
    description: Cloud credentials are used by several managed services to interact
      with the cloud provider that the cluster runs on.
    digest: 4ea7f96da053f69b3e87818115ac8e326227f9644a7ee09af1eec63400ae8fc3
    name: cloud-credentials
    urls:
    - cloud-creds/cloud-credentials-3.0.0.tgz
    version: 3.0.0
  dex:
  - apiVersion: v1
    appVersion: 2.24.0
    created: "2020-10-28T12:50:50.630467498-06:00"
    description: OpenID Connect Identity (OIDC) and OAuth 2.0 Provider with Pluggable
      Connectors
    digest: 3e32467caf3150019776f3bef478af643b89e6da93a1bedddbcad58bfdce2c10
    home: https://github.com/dexidp/dex/
    icon: https://github.com/dexidp/dex/raw/master/Documentation/logos/dex-glyph-color.png
    keywords:
    - dex
    - oidc
    maintainers:
    - email: Kevin.Fox@pnnl.gov
      name: kfox1111
    - email: shane.starcher@gmail.com
      name: sstarcher
    - email: pete.brown@powerhrg.com
      name: rendhalver
    - email: vi7alya@gmail.com
      name: vi7
    name: dex
    urls:
    - dex/dex-2.12.0.tgz
    version: 2.12.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 7.6.2
    created: "2020-10-28T12:50:50.632043591-06:00"
    description: Official Elastic helm chart for Elasticsearch
    digest: bfe469bbea16f107297a42f5ea8c3c93d6606d73b90770d73c0e3d6ad9a38c56
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - elasticsearch/elasticsearch-7.6.2.tgz
    version: 7.6.2
  harbor:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-10-28T12:50:50.638379536-06:00"
    description: An open source trusted cloud native registry that stores, signs,
      and scans content
    digest: 3a93c03a65ab678903045b9b39d07c93a05f904157652d64bd45b87f6ecae51c
    home: https://goharbor.io
    icon: https://raw.githubusercontent.com/goharbor/website/master/static/img/logos/harbor-icon-color.png
    keywords:
    - docker
    - registry
    - harbor
    maintainers:
    - email: yinw@vmware.com
      name: Wenkai Yin
    - email: hweiwei@vmware.com
      name: Weiwei He
    - email: dengq@vmware.com
      name: Qian Deng
    name: harbor
    sources:
    - https://github.com/goharbor/harbor
    - https://github.com/goharbor/harbor-helm
    urls:
    - harbor/harbor-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v1
    appVersion: 2.0.3
    created: "2020-10-28T12:50:50.634732531-06:00"
    description: An open source trusted cloud native registry that stores, signs,
      and scans content
    digest: e069f3347388596474ed730911fc8647a6728a753b937cf9a13ec10552c6e2a4
    home: https://goharbor.io
    icon: https://raw.githubusercontent.com/goharbor/website/master/static/img/logos/harbor-icon-color.png
    keywords:
    - docker
    - registry
    - harbor
    maintainers:
    - email: yinw@vmware.com
      name: Wenkai Yin
    - email: hweiwei@vmware.com
      name: Weiwei He
    - email: dengq@vmware.com
      name: Qian Deng
    name: harbor
    sources:
    - https://github.com/goharbor/harbor
    - https://github.com/goharbor/harbor-helm
    urls:
    - harbor/harbor-1.4.3.tgz
    version: 1.4.3
  kam:
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2020-10-28T12:50:50.63879798-06:00"
    description: KaaS Access Manager
    digest: de2f94cc91f17eb2cfa3c5aecebc922a8ec0502aff2a84e8b5ad1cd85d342354
    name: kam
    urls:
    - kam/kam-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-28T12:50:50.615603013-06:00"
